FROM    nginx
COPY	nginx.default.conf /etc/nginx/nginx.conf
#COPY    api.vvlunch.co.uk /etc/nginx/conf.d/api.vvlunch.co.uk.conf
COPY    api.vvlunch.co.uk /temp/api-conf
COPY    reconfigure.sh /temp/reconfigure.sh
