FROM    nginx
COPY	nginx.default.conf /etc/nginx/nginx.conf
COPY    crossbowsites.conf /etc/nginx/conf.d/crossbowsites.conf
#COPY   crossbowsites.conf /temp/api-conf
#COPY   reconfigure.sh /temp/reconfigure.sh
